module.exports.Logger = require('./Logger');
module.exports.EventHandler = require('./EventHandler');
module.exports.CommandsBuilder = require('./CommandsBuilder');
module.exports.ts2time = require('./ts2time');
module.exports.Command = require('./Command');
module.exports.EmbedBuild = require('./EmbedBuild');
const EmbedUtil = require('./EmbedBuild');
module.exports.CustomEmbed = EmbedUtil.CustomEmbed;
module.exports.GCP = require('./gcp');